"""drop_document_chunks_use_langchain

Revision ID: 0ad8965a329e
Revises: c2b6a544803b
Create Date: 2026-05-26 12:39:36.629591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0ad8965a329e'
down_revision: Union[str, None] = 'c2b6a544803b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document_chunks')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_chunks',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('document_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('page_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('chunk_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=3072), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('document_chunks_document_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('document_chunks_pkey'))
    )
    # ### end Alembic commands ###
