"""add doc_type to documents

Revision ID: 4799c759e82f
Revises: 73fdd8cf1178
Create Date: 2026-05-27 14:07:48.996205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4799c759e82f'
down_revision: Union[str, None] = '73fdd8cf1178'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('doc_type', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'doc_type')
    # ### end Alembic commands ###
