"""add_video_fields_to_documents

Revision ID: 47f046cfd649
Revises: 48fb0de80fc0
Create Date: 2026-05-28 12:21:26.851119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '47f046cfd649'
down_revision: Union[str, None] = '48fb0de80fc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('source_url', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('duration_seconds', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('thumbnail_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'thumbnail_url')
    op.drop_column('documents', 'duration_seconds')
    op.drop_column('documents', 'source_url')
    # ### end Alembic commands ###
