"""add toc to documents

Revision ID: 48fb0de80fc0
Revises: fe13e6e3ef26
Create Date: 2026-05-27 21:24:26.720436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '48fb0de80fc0'
down_revision: Union[str, None] = 'fe13e6e3ef26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('toc', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'toc')
    # ### end Alembic commands ###
