"""replace_google_id_with_oauth_provider_columns

Revision ID: 73fdd8cf1178
Revises: 78ada6e81377
Create Date: 2026-05-27 10:17:41.156811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '73fdd8cf1178'
down_revision: Union[str, None] = '78ada6e81377'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Existing rows used google_id for identity and cannot be migrated without
    # knowing the provider. TRUNCATE CASCADE clears users and all dependent rows.
    op.execute("""
        DO $$ BEGIN
            IF EXISTS (
                SELECT 1 FROM information_schema.tables
                WHERE table_schema = 'public' AND table_name = 'users'
            ) THEN
                TRUNCATE TABLE users CASCADE;
            END IF;
        END $$;
    """)
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('oauth_provider', sa.String(length=32), nullable=False))
    op.add_column('users', sa.Column('oauth_provider_id', sa.String(length=128), nullable=False))
    op.drop_constraint(op.f('users_google_id_key'), 'users', type_='unique')
    op.create_unique_constraint('uq_users_oauth', 'users', ['oauth_provider', 'oauth_provider_id'])
    op.drop_column('users', 'google_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_id', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.drop_constraint('uq_users_oauth', 'users', type_='unique')
    op.create_unique_constraint(op.f('users_google_id_key'), 'users', ['google_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'oauth_provider_id')
    op.drop_column('users', 'oauth_provider')
    # ### end Alembic commands ###
