"""replace_changepay_auth_with_google_oauth

Revision ID: 78ada6e81377
Revises: 0ad8965a329e
Create Date: 2026-05-27 09:43:15.184635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '78ada6e81377'
down_revision: Union[str, None] = '0ad8965a329e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Drop old ChangePay auth data — existing rows cannot have google_id values.
    # Any prior user accounts are invalid after this migration.
    # TRUNCATE CASCADE clears users and all child tables in one shot.
    op.execute("TRUNCATE TABLE users CASCADE")

    # Add google_id as nullable first (table may have rows in production migrations)
    op.add_column('users', sa.Column('google_id', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('picture_url', sa.Text(), nullable=True))

    # Now enforce NOT NULL (safe — table is empty after the delete above)
    op.alter_column('users', 'google_id', nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    op.drop_constraint(op.f('users_phone_key'), 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['email'])
    op.create_unique_constraint(None, 'users', ['google_id'])
    op.drop_column('users', 'phone')
    op.drop_column('users', 'changepay_profile_token')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('changepay_profile_token', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint(op.f('users_phone_key'), 'users', ['phone'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('users', 'picture_url')
    op.drop_column('users', 'google_id')
    # ### end Alembic commands ###
