"""add_video_source_to_documents

Revision ID: 7fb9f84d762b
Revises: 47f046cfd649
Create Date: 2026-05-28 12:42:24.002968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7fb9f84d762b'
down_revision: Union[str, None] = '47f046cfd649'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('video_source', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'video_source')
    # ### end Alembic commands ###
