"""add_file_name_to_documents

Revision ID: a8ec88b5e21a
Revises: b2b1c6664925
Create Date: 2026-05-27 16:46:33.331900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a8ec88b5e21a'
down_revision: Union[str, None] = 'b2b1c6664925'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add nullable first, backfill from title, then enforce NOT NULL
    op.add_column('documents', sa.Column('file_name', sa.String(length=500), nullable=True))
    op.execute("UPDATE documents SET file_name = title")
    op.alter_column('documents', 'file_name', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'file_name')
    # ### end Alembic commands ###
