"""add expected_summary_count to documents

Revision ID: b2b1c6664925
Revises: 4799c759e82f
Create Date: 2026-05-27 16:31:24.292294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b2b1c6664925'
down_revision: Union[str, None] = '4799c759e82f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('expected_summary_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'expected_summary_count')
    # ### end Alembic commands ###
