"""add_fk_refresh_tokens_user_id

Revision ID: c2b6a544803b
Revises: 5af8b17f15b6
Create Date: 2026-05-25 15:13:20.774204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c2b6a544803b'
down_revision: Union[str, None] = '5af8b17f15b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'refresh_tokens', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'refresh_tokens', type_='foreignkey')
    # ### end Alembic commands ###
