"""add_sort_order_to_summaries

Revision ID: fe13e6e3ef26
Revises: a8ec88b5e21a
Create Date: 2026-05-27 18:51:49.747949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fe13e6e3ef26'
down_revision: Union[str, None] = 'a8ec88b5e21a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('summaries', sa.Column('sort_order', sa.Integer(), nullable=True))
    op.execute("UPDATE summaries SET sort_order = 0")
    op.alter_column('summaries', 'sort_order', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('summaries', 'sort_order')
    # ### end Alembic commands ###
